channels:
  - conda-forge
dependencies:
  - python>=3.10
  - cutde
  - fiona
  - geopandas>=1.0.0
  - git-lfs
  - matplotlib
  - meshio
  - netCDF4
  - numpy
  - openpyxl
  - rasterio
  - scipy
  - shapely
